apiVersion: batch/v1
kind: Job
metadata:
  name: linkstore-migration
  namespace: linkstore
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      tolerations:
        - key: "podtype"
          operator: "Equal"
          value: "workload"
          effect: "NoSchedule"
      serviceAccountName: linkstore-sa
      containers:
        - name: migrate
          image: 674288684391.dkr.ecr.us-east-1.amazonaws.com/link-store:latest
          command: ["python", "migrate.py"]
          envFrom:
            - secretRef:
                name: linkstore-db-secret
          volumeMounts:
            - name: db-secrets
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: db-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "linkstore-db-credentials"