apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkstore-sa
  namespace: linkstore

  #Note this service account permissions are already configured in terraform with a aws_eks_pod_identity_association resource, the service account gets its permissions from the pod identity agent